web:
  build: .
  environment:
    - THAT_COUCH_DB=http://couch:5984
    - THAT_AUTH_KEY=deadbeef
  links:
    - couch
  ports:
    - "8080:8080"
  volumes:
    - ".:/go/src/github.com/mike-douglas/that"

couch:
  image: couchdb
  ports:
    - "8082:5984"
